export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAIL = 'GET_EVENTS_FAIL'

export const GET_PARTICIPANTS_REQUEST = 'GET_PARTICIPANTS_REQUEST'
export const GET_PARTICIPANTS_SUCCESS = 'GET_PARTICIPANTS_SUCCESS'
export const GET_PARTICIPANTS_FAIL = 'GET_PARTICIPANTS_FAIL'

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const ADD_EVENT_FAIL = 'ADD_EVENT_FAIL'
export const ADD_EVENT_RESET = 'ADD_EVENT_RESET'

export const GET_SINGLE_EVENT_REQUEST = 'GET_SINGLE_EVENT_REQUEST'
export const GET_SINGLE_EVENT_SUCCESS = 'GET_SINGLE_EVENT_SUCCESS'
export const GET_SINGLE_EVENT_FAIL = 'GET_SINGLE_EVENT_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'